name: generate-builds

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Install container dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc libgl1-mesa-dev xorg-dev libfuse2

    - name: Install Fyne tool
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Package Fyne app
      run: fyne package --os linux --release

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: marina-linux
        path: marina.appimage

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        update: true

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Install container dependencies
      run: >
        pacman -Syu &&
        pacman --noconfirm -S git zip mingw-w64-x86_64-toolchain

    - name: Install Fyne tool
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Package
      run: fyne package --os windows --release

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: marina-windows
        path: marina

  build-mac:
    runs-on: macos-14
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Install Fyne tool
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Package
      run: fyne package --os darwin --release

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: marina-mac
        path: marina.dmg
